CREATE TEMP FUNCTION getCampaignStatus(status INT64)
  AS (['UNSPECIFIED','UNKNOWN','ENABLED','PAUSED','REMOVED'][OFFSET(status)]);

CREATE TEMP FUNCTION getAdGroupAdStatus(status INT64)
  AS (['UNSPECIFIED','UNKNOWN','ENABLED','PAUSED','REMOVED'][OFFSET(status)]);

CREATE TEMP FUNCTION getCampaignType(status INT64)
  AS (['UNSPECIFIED','UNKNOWN','SEARCH','DISPLAY','SHOPPING','HOTEL','VIDEO','MULTI_CHANNEL','LOCAL','SMART'][OFFSET(status)]);

CREATE TEMP FUNCTION getCampaignSubType(status INT64)
  AS (['UNSPECIFIED','UNKNOWN','SEARCH_MOBILE_APP','DISPLAY_MOBILE_APP','SEARCH_EXPRESS','DISPLAY_EXPRESS','SHOPPING_SMART_ADS','DISPLAY_GMAIL_AD','DISPLAY_SMART_CAMPAIGN','VIDEO_OUTSTREAM','VIDEO_ACTION','VIDEO_NON_SKIPPABLE','APP_CAMPAIGN','APP_CAMPAIGN_FOR_ENGAGEMENT','LOCAL_CAMPAIGN','SHOPPING_COMPARISON_LISTING_ADS','SMART_CAMPAIGN','VIDEO_SEQUENCE'][OFFSET(status)]);

CREATE TEMP FUNCTION getPolicyApprovalStatus(status INT64)
  AS (['UNSPECIFIED','UNKNOWN','DISAPPROVED','APPROVED_LIMITED','APPROVED','AREA_OF_INTEREST_ONLY'][OFFSET(status)]);

CREATE TEMP FUNCTION getPolicyReviewStatus(status INT64)
  AS (['UNSPECIFIED','UNKNOWN','REVIEW_IN_PROGRESS','REVIEWED','UNDER_APPEAL','ELIGIBLE_MAY_SERVE'][OFFSET(status)]);

CREATE TEMP FUNCTION getAdType(TypeCode INT64)
AS
(CASE TypeCode
  WHEN 0 THEN 'UNSPECIFIED'
  WHEN 1 THEN 'UNKNOWN'
  WHEN 2 THEN 'TEXT_AD'
  WHEN 3 THEN 'EXPANDED_TEXT_AD'
  WHEN 6 THEN 'CALL_ONLY_AD'
  WHEN 7 THEN 'EXPANDED_DYNAMIC_SEARCH_AD'
  WHEN 8 THEN 'HOTEL_AD'
  WHEN 9 THEN 'SHOPPING_SMART_AD'
  WHEN 10 THEN 'SHOPPING_PRODUCT_AD'
  WHEN 12 THEN 'VIDEO_AD'
  WHEN 13 THEN 'GMAIL_AD'
  WHEN 14 THEN 'IMAGE_AD'
  WHEN 15 THEN 'RESPONSIVE_SEARCH_AD'
  WHEN 16 THEN 'LEGACY_RESPONSIVE_DISPLAY_AD'
  WHEN 17 THEN 'APP_AD'
  WHEN 18 THEN 'LEGACY_APP_INSTALL_AD'
  WHEN 19 THEN 'RESPONSIVE_DISPLAY_AD'
  WHEN 20 THEN 'LOCAL_AD'
  WHEN 21 THEN 'HTML5_UPLOAD_AD'
  WHEN 22 THEN 'DYNAMIC_HTML5_AD'
  WHEN 23 THEN 'APP_ENGAGEMENT_AD'
  WHEN 24 THEN 'SHOPPING_COMPARISON_LISTING_AD'
  WHEN 25 THEN 'VIDEO_BUMPER_AD'
  WHEN 26 THEN 'VIDEO_NON_SKIPPABLE_IN_STREAM_AD'
  WHEN 27 THEN 'VIDEO_OUTSTREAM_AD'
  WHEN 28 THEN 'VIDEO_TRUEVIEW_DISCOVERY_AD'
  WHEN 29 THEN 'VIDEO_TRUEVIEW_IN_STREAM_AD'
  WHEN 30 THEN 'VIDEO_RESPONSIVE_AD'
 END);

select
distinct
a.customer.id as Customer_ID,
a.campaign.id as Campaign_id,
a.adGroupAd.ad.id,
getPolicyApprovalStatus(a.adGroupAd.policySummary.approvalStatus) as Approval_status,
getPolicyReviewStatus(a.adGroupAd.policySummary.reviewStatus) as Review_status,
getAdType(a.adGroupAd.ad.type) as Ad_type,
a.campaign.name as Campaign_name,
a.customer.descriptiveName as Account,
getCampaignStatus(a.campaign.status) as Campaign_status,
getCampaignType(a.campaign.advertisingChannelType) as Campaign_type,
getCampaignSubType(a.campaign.advertisingChannelSubType) as Campaign_sub_type
from `${datasetId}.report_base_campaign_ads_approval` a

where  date(_partitionTime) = PARSE_DATE('%Y%m%d', '${partitionDay}')